"""Sync and async Python clients for the herdr Unix socket API."""

from .async_client import AsyncHerdrClient, AsyncSubscription
from .exceptions import HerdrApiError, HerdrClientError
from .interfaces import (
    AsyncClientProtocol,
    AsyncSubscriptionProtocol,
    SubscriptionProtocol,
    SyncClientProtocol,
)
from .protocol import (
    CANONICAL_METHODS,
    CONVENIENCE_METHODS,
    METHOD_SCHEMAS,
    NOT_IMPLEMENTED_METHODS,
    SCHEMA_PROTOCOL,
    SCHEMA_VERSION,
    SPECIAL_METHODS,
)
from .schema import (
    OFFICIAL_SCHEMA_PROTOCOL,
    OFFICIAL_SCHEMA_SHA256,
    OFFICIAL_SCHEMA_URL,
    OFFICIAL_SCHEMA_VERSION,
)
from .sync import HerdrClient, Subscription
from .transport import DEFAULT_SOCKET_CANDIDATES, resolve_socket_path
from .types import (
    ErrorEnvelope,
    ErrorObject,
    EventEnvelope,
    EventSubscription,
    JsonObject,
    JSONValue,
    OkResult,
    OutputMatch,
    OutputMatchedResult,
    PaneInfo,
    PaneListResult,
    PaneReadParams,
    PaneReadResponse,
    PaneReadResult,
    PongResult,
    ReadFormat,
    ReadSource,
    RequestEnvelope,
    ResponseEnvelope,
    SubscriptionAck,
    SuccessEnvelope,
    TabInfo,
    TabListResult,
    WorkspaceInfo,
    WorkspaceListResult,
)

__all__ = [
    "CANONICAL_METHODS",
    "CONVENIENCE_METHODS",
    "DEFAULT_SOCKET_CANDIDATES",
    "METHOD_SCHEMAS",
    "NOT_IMPLEMENTED_METHODS",
    "OFFICIAL_SCHEMA_PROTOCOL",
    "OFFICIAL_SCHEMA_SHA256",
    "OFFICIAL_SCHEMA_URL",
    "OFFICIAL_SCHEMA_VERSION",
    "SCHEMA_PROTOCOL",
    "SCHEMA_VERSION",
    "SPECIAL_METHODS",
    "AsyncClientProtocol",
    "AsyncHerdrClient",
    "AsyncSubscription",
    "AsyncSubscriptionProtocol",
    "ErrorEnvelope",
    "ErrorObject",
    "EventEnvelope",
    "EventSubscription",
    "HerdrApiError",
    "HerdrClient",
    "HerdrClientError",
    "JSONValue",
    "JsonObject",
    "OkResult",
    "OutputMatch",
    "OutputMatchedResult",
    "PaneInfo",
    "PaneListResult",
    "PaneReadParams",
    "PaneReadResponse",
    "PaneReadResult",
    "PongResult",
    "ReadFormat",
    "ReadSource",
    "RequestEnvelope",
    "ResponseEnvelope",
    "Subscription",
    "SubscriptionAck",
    "SubscriptionProtocol",
    "SuccessEnvelope",
    "SyncClientProtocol",
    "TabInfo",
    "TabListResult",
    "WorkspaceInfo",
    "WorkspaceListResult",
    "resolve_socket_path",
]
