# This file is generated by tools/generate_models.py. Do not edit.
"""Generated TypedDict models from the pinned Herdr JSON Schema."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Literal, NotRequired, Required, TypedDict

type JSONScalar = bool | int | float | str | None
type JSONValue = JSONScalar | list[JSONValue] | Mapping[str, JSONValue]
type JsonObject = dict[str, JSONValue]

# request definitions


class RequestAgentPromptParams(TypedDict, total=False):
    target: Required[str]
    text: Required[str]
    wait: NotRequired[RequestAgentPromptWaitOptions | None]


class RequestAgentPromptWaitOptions(TypedDict, total=False):
    timeout_ms: NotRequired[int | None]
    until: NotRequired[list[RequestAgentStatus]]


class RequestAgentReadParams(TypedDict, total=False):
    format: NotRequired[RequestReadFormat]
    lines: NotRequired[int | None]
    source: Required[RequestReadSource]
    strip_ansi: NotRequired[bool]
    target: Required[str]


class RequestAgentRenameParams(TypedDict, total=False):
    name: NotRequired[str | None]
    target: Required[str]


class RequestAgentSendKeysParams(TypedDict):
    keys: list[str]
    target: str


class RequestAgentStartParams(TypedDict, total=False):
    args: NotRequired[list[str]]
    kind: Required[str]
    name: Required[str]
    pane_id: Required[str]
    timeout_ms: NotRequired[int | None]


type RequestAgentStatus = Literal["idle", "working", "blocked", "done", "unknown"]


class RequestAgentTarget(TypedDict):
    target: str


type RequestAgentViewBuiltinField = Literal[
    "status",
    "workspace_id",
    "tab_id",
    "pane_id",
    "agent",
    "seen",
    "state_change_seq",
]


type RequestAgentViewBuiltinSortField = Literal[
    "workspace_order",
    "tab_order",
    "pane_order",
    "attention",
    "status",
    "agent",
    "seen",
    "state_change_seq",
]


class RequestAgentViewClearParams(TypedDict, total=False):
    source: NotRequired[str | None]


type RequestAgentViewContext = Literal["current_workspace_id", "current_tab_id"]


class RequestAgentViewFieldVariant2(TypedDict):
    token: str


type RequestAgentViewField = (
    RequestAgentViewBuiltinField | RequestAgentViewFieldVariant2
)


class RequestAgentViewFilterVariant1(TypedDict):
    filters: list[RequestAgentViewFilter]
    op: Literal["all"]


class RequestAgentViewFilterVariant2(TypedDict):
    filters: list[RequestAgentViewFilter]
    op: Literal["any"]


class RequestAgentViewFilterVariant3(TypedDict):
    filter: RequestAgentViewFilter
    op: Literal["not"]


class RequestAgentViewFilterVariant4(TypedDict):
    field: RequestAgentViewField
    op: Literal["eq"]
    value: RequestAgentViewValue


class RequestAgentViewFilterVariant5(TypedDict):
    field: RequestAgentViewField
    op: Literal["in"]
    values: list[RequestAgentViewValue]


class RequestAgentViewFilterVariant6(TypedDict):
    field: RequestAgentViewField
    op: Literal["exists"]


type RequestAgentViewFilter = (
    RequestAgentViewFilterVariant1
    | RequestAgentViewFilterVariant2
    | RequestAgentViewFilterVariant3
    | RequestAgentViewFilterVariant4
    | RequestAgentViewFilterVariant5
    | RequestAgentViewFilterVariant6
)


class RequestAgentViewSetParams(TypedDict, total=False):
    filter: NotRequired[RequestAgentViewFilter | None]
    label: NotRequired[str | None]
    sort: NotRequired[list[RequestAgentViewSort]]
    source: Required[str]


class RequestAgentViewSort(TypedDict, total=False):
    field: Required[RequestAgentViewSortField]
    order: NotRequired[RequestAgentViewSortOrder]


class RequestAgentViewSortFieldVariant2(TypedDict):
    token: str


type RequestAgentViewSortField = (
    RequestAgentViewBuiltinSortField | RequestAgentViewSortFieldVariant2
)


type RequestAgentViewSortOrder = Literal["asc", "desc"]


class RequestAgentViewValueVariant4(TypedDict):
    context: RequestAgentViewContext


type RequestAgentViewValue = str | bool | int | RequestAgentViewValueVariant4


class RequestAgentWaitParams(TypedDict, total=False):
    target: Required[str]
    timeout_ms: NotRequired[int | None]
    until: NotRequired[list[RequestAgentStatus]]


class RequestClientShellSurfaceSetParams(TypedDict):
    active: bool


class RequestClientWindowTitleSetParams(TypedDict):
    title: str


class RequestCommandInvokeParams(TypedDict, total=False):
    command_id: Required[str]
    pane_id: NotRequired[str | None]
    selection: NotRequired[RequestPaneSelectionReadParams | None]
    tab_id: NotRequired[str | None]
    workspace_id: NotRequired[str | None]


type RequestEmptyParams = JsonObject


class RequestEventMatchVariant1(TypedDict, total=False):
    event: Required[Literal["workspace_created"]]
    workspace_id: NotRequired[str | None]


class RequestEventMatchVariant2(TypedDict):
    event: Literal["workspace_updated"]
    workspace_id: str


class RequestEventMatchVariant3(TypedDict):
    event: Literal["workspace_closed"]
    workspace_id: str


class RequestEventMatchVariant4(TypedDict, total=False):
    event: Required[Literal["workspace_renamed"]]
    label: NotRequired[str | None]
    workspace_id: Required[str]


class RequestEventMatchVariant5(TypedDict):
    event: Literal["workspace_moved"]
    workspace_id: str


class RequestEventMatchVariant6(TypedDict):
    event: Literal["workspace_focused"]
    workspace_id: str


class RequestEventMatchVariant7(TypedDict, total=False):
    event: Required[Literal["tab_created"]]
    tab_id: NotRequired[str | None]
    workspace_id: NotRequired[str | None]


class RequestEventMatchVariant8(TypedDict):
    event: Literal["tab_closed"]
    tab_id: str


class RequestEventMatchVariant9(TypedDict, total=False):
    event: Required[Literal["tab_renamed"]]
    label: NotRequired[str | None]
    tab_id: Required[str]


class RequestEventMatchVariant10(TypedDict):
    event: Literal["tab_moved"]
    tab_id: str


class RequestEventMatchVariant11(TypedDict):
    event: Literal["tab_focused"]
    tab_id: str


class RequestEventMatchVariant12(TypedDict, total=False):
    event: Required[Literal["pane_created"]]
    pane_id: NotRequired[str | None]
    workspace_id: NotRequired[str | None]


class RequestEventMatchVariant13(TypedDict):
    event: Literal["pane_closed"]
    pane_id: str


class RequestEventMatchVariant14(TypedDict):
    event: Literal["pane_focused"]
    pane_id: str


class RequestEventMatchVariant15(TypedDict):
    event: Literal["pane_moved"]
    pane_id: str


class RequestEventMatchVariant16(TypedDict, total=False):
    event: Required[Literal["pane_output_changed"]]
    min_revision: NotRequired[int | None]
    pane_id: Required[str]


class RequestEventMatchVariant17(TypedDict):
    event: Literal["pane_exited"]
    pane_id: str


class RequestEventMatchVariant18(TypedDict, total=False):
    agent: NotRequired[str | None]
    event: Required[Literal["pane_agent_detected"]]
    pane_id: Required[str]


class RequestEventMatchVariant19(TypedDict):
    agent_status: RequestAgentStatus
    event: Literal["pane_agent_status_changed"]
    pane_id: str


type RequestEventMatch = (
    RequestEventMatchVariant1
    | RequestEventMatchVariant2
    | RequestEventMatchVariant3
    | RequestEventMatchVariant4
    | RequestEventMatchVariant5
    | RequestEventMatchVariant6
    | RequestEventMatchVariant7
    | RequestEventMatchVariant8
    | RequestEventMatchVariant9
    | RequestEventMatchVariant10
    | RequestEventMatchVariant11
    | RequestEventMatchVariant12
    | RequestEventMatchVariant13
    | RequestEventMatchVariant14
    | RequestEventMatchVariant15
    | RequestEventMatchVariant16
    | RequestEventMatchVariant17
    | RequestEventMatchVariant18
    | RequestEventMatchVariant19
)


class RequestEventsSubscribeParams(TypedDict):
    subscriptions: list[RequestSubscription]


class RequestEventsWaitParams(TypedDict, total=False):
    match_event: Required[RequestEventMatch]
    timeout_ms: NotRequired[int | None]


class RequestIntegrationInstallParams(TypedDict):
    target: RequestIntegrationTarget


type RequestIntegrationTarget = Literal[
    "pi",
    "omp",
    "claude",
    "codex",
    "copilot",
    "devin",
    "droid",
    "kimi",
    "opencode",
    "kilo",
    "hermes",
    "qodercli",
    "qwen",
    "cursor",
    "mastracode",
    "antigravity_cli",
    "grok",
]


class RequestIntegrationUninstallParams(TypedDict):
    target: RequestIntegrationTarget


class RequestLayoutApplyParams(TypedDict, total=False):
    focus: NotRequired[bool]
    root: Required[RequestLayoutNode]
    tab_id: NotRequired[str | None]
    tab_label: NotRequired[str | None]
    workspace_id: NotRequired[str | None]


class RequestLayoutExportParams(TypedDict, total=False):
    pane_id: NotRequired[str | None]
    tab_id: NotRequired[str | None]


class RequestLayoutNodeVariant1(TypedDict, total=False):
    command: NotRequired[list[JsonObject] | None]
    cwd: NotRequired[str | None]
    env: NotRequired[dict[str, str]]
    label: NotRequired[str | None]
    pane_id: NotRequired[str | None]
    type: Required[Literal["pane"]]


class RequestLayoutNodeVariant2(TypedDict):
    direction: RequestSplitDirection
    first: RequestLayoutNode
    ratio: int
    second: RequestLayoutNode
    type: Literal["split"]


type RequestLayoutNode = RequestLayoutNodeVariant1 | RequestLayoutNodeVariant2


class RequestLayoutSetSplitRatioParams(TypedDict, total=False):
    pane_id: NotRequired[str | None]
    path: Required[list[bool]]
    ratio: Required[int]
    tab_id: NotRequired[str | None]


class RequestNotificationShowParams(TypedDict, total=False):
    body: NotRequired[str | None]
    position: NotRequired[RequestToastHerdrPosition | None]
    sound: NotRequired[RequestNotificationShowSound]
    title: Required[str]


type RequestNotificationShowSound = Literal["none", "done", "request"]


class RequestOutputMatchVariant1(TypedDict):
    type: Literal["substring"]
    value: str


class RequestOutputMatchVariant2(TypedDict):
    type: Literal["regex"]
    value: str


type RequestOutputMatch = RequestOutputMatchVariant1 | RequestOutputMatchVariant2


type RequestPaneAgentState = Literal["idle", "working", "blocked", "unknown"]


class RequestPaneClearAgentAuthorityParams(TypedDict, total=False):
    pane_id: Required[str]
    seq: NotRequired[int | None]
    source: NotRequired[str | None]


type RequestPaneCopyMotion = Literal[
    "line_end",
    "first_non_blank",
    "next_word_start",
    "previous_word_start",
    "next_word_end",
    "next_big_word_start",
    "previous_big_word_start",
    "next_big_word_end",
    "previous_paragraph",
    "next_paragraph",
]


class RequestPaneCopyMotionParams(TypedDict, total=False):
    content_revision: NotRequired[int | None]
    cursor: Required[RequestPaneTextPoint]
    motion: Required[RequestPaneCopyMotion]
    pane_id: Required[str]


type RequestPaneCopySearchDirection = Literal["forward", "backward"]


class RequestPaneCopySearchParams(TypedDict, total=False):
    content_revision: Required[int]
    cursor: Required[RequestPaneTextPoint]
    direction: Required[RequestPaneCopySearchDirection]
    pane_id: Required[str]
    previous: NotRequired[RequestPaneTextRange | None]
    query: Required[str]


class RequestPaneCurrentParams(TypedDict, total=False):
    caller_pane_id: NotRequired[str | None]


type RequestPaneDirection = Literal["left", "right", "up", "down"]


class RequestPaneEdgesParams(TypedDict, total=False):
    pane_id: NotRequired[str | None]


class RequestPaneFocusDirectionParams(TypedDict, total=False):
    direction: Required[RequestPaneDirection]
    pane_id: NotRequired[str | None]


class RequestPaneGraphicsClearParams(TypedDict, total=False):
    layer_id: NotRequired[str | None]
    pane_id: Required[str]


type RequestPaneGraphicsFormat = Literal["png", "rgb", "rgba", "bgra"]


class RequestPaneGraphicsPlacementParams(TypedDict, total=False):
    grid_cols: NotRequired[int]
    grid_rows: NotRequired[int]
    viewport_col: NotRequired[int]
    viewport_row: NotRequired[int]


class RequestPaneGraphicsSetParams(TypedDict, total=False):
    data_base64: NotRequired[str]
    format: Required[RequestPaneGraphicsFormat]
    image_height: Required[int]
    image_width: Required[int]
    layer_id: NotRequired[str | None]
    pane_id: Required[str]
    placement: NotRequired[RequestPaneGraphicsPlacementParams]
    z_index: NotRequired[int]


class RequestPaneInputSetParams(TypedDict):
    pane_id: str
    right_click: RequestPaneRightClickTarget


class RequestPaneLayoutParams(TypedDict, total=False):
    pane_id: NotRequired[str | None]


class RequestPaneLinkActivateParams(TypedDict, total=False):
    col: Required[int]
    content_revision: NotRequired[int | None]
    offset_from_bottom: NotRequired[int | None]
    pane_id: Required[str]
    viewport_row: Required[int]


class RequestPaneListParams(TypedDict, total=False):
    workspace_id: NotRequired[str | None]


class RequestPaneMoveDestinationVariant1(TypedDict, total=False):
    ratio: NotRequired[int | None]
    split: Required[RequestSplitDirection]
    tab_id: Required[str]
    target_pane_id: NotRequired[str | None]
    type: Required[Literal["tab"]]


class RequestPaneMoveDestinationVariant2(TypedDict, total=False):
    label: NotRequired[str | None]
    type: Required[Literal["new_tab"]]
    workspace_id: NotRequired[str | None]


class RequestPaneMoveDestinationVariant3(TypedDict, total=False):
    label: NotRequired[str | None]
    tab_label: NotRequired[str | None]
    type: Required[Literal["new_workspace"]]


type RequestPaneMoveDestination = (
    RequestPaneMoveDestinationVariant1
    | RequestPaneMoveDestinationVariant2
    | RequestPaneMoveDestinationVariant3
)


class RequestPaneMoveParams(TypedDict, total=False):
    destination: Required[RequestPaneMoveDestination]
    focus: NotRequired[bool]
    pane_id: Required[str]


class RequestPaneNeighborParams(TypedDict, total=False):
    direction: Required[RequestPaneDirection]
    pane_id: NotRequired[str | None]


class RequestPaneProcessInfoParams(TypedDict, total=False):
    pane_id: NotRequired[str | None]


class RequestPaneReadParams(TypedDict, total=False):
    format: NotRequired[RequestReadFormat]
    lines: NotRequired[int | None]
    pane_id: Required[str]
    source: Required[RequestReadSource]
    strip_ansi: NotRequired[bool]


class RequestPaneReleaseAgentParams(TypedDict, total=False):
    agent: Required[str]
    pane_id: Required[str]
    seq: NotRequired[int | None]
    source: Required[str]


class RequestPaneRenameParams(TypedDict, total=False):
    label: NotRequired[str | None]
    pane_id: Required[str]


class RequestPaneReportAgentParams(TypedDict, total=False):
    agent: Required[str]
    agent_session_id: NotRequired[str | None]
    agent_session_path: NotRequired[str | None]
    message: NotRequired[str | None]
    pane_id: Required[str]
    seq: NotRequired[int | None]
    source: Required[str]
    state: Required[RequestPaneAgentState]


class RequestPaneReportAgentSessionParams(TypedDict, total=False):
    agent: Required[str]
    agent_session_id: NotRequired[str | None]
    agent_session_path: NotRequired[str | None]
    pane_id: Required[str]
    seq: NotRequired[int | None]
    session_start_source: NotRequired[str | None]
    source: Required[str]


class RequestPaneReportMetadataParams(TypedDict, total=False):
    agent: NotRequired[str | None]
    applies_to_source: NotRequired[str | None]
    clear_display_agent: NotRequired[bool]
    clear_state_labels: NotRequired[bool]
    clear_title: NotRequired[bool]
    display_agent: NotRequired[str | None]
    pane_id: Required[str]
    seq: NotRequired[int | None]
    source: Required[str]
    state_labels: NotRequired[dict[str, str]]
    title: NotRequired[str | None]
    tokens: NotRequired[dict[str, str | None]]
    ttl_ms: NotRequired[int | None]


class RequestPaneResizeParams(TypedDict, total=False):
    amount: NotRequired[int | None]
    direction: Required[RequestPaneDirection]
    pane_id: NotRequired[str | None]


type RequestPaneRightClickTarget = Literal["herdr", "pane"]


class RequestPaneScrollParams(TypedDict):
    offset_from_bottom: int
    pane_id: str


class RequestPaneSelectionReadParams(TypedDict, total=False):
    anchor: Required[RequestPaneTextPoint]
    content_revision: NotRequired[int | None]
    cursor: Required[RequestPaneTextPoint]
    pane_id: Required[str]


class RequestPaneSendInputParams(TypedDict, total=False):
    keys: NotRequired[list[str]]
    pane_id: Required[str]
    text: NotRequired[str]


class RequestPaneSendKeysParams(TypedDict):
    keys: list[str]
    pane_id: str


class RequestPaneSendTextParams(TypedDict):
    pane_id: str
    text: str


class RequestPaneSplitParams(TypedDict, total=False):
    cwd: NotRequired[str | None]
    direction: Required[RequestSplitDirection]
    env: NotRequired[dict[str, str]]
    focus: NotRequired[bool]
    ratio: NotRequired[int | None]
    right_click: NotRequired[RequestPaneRightClickTarget]
    target_pane_id: NotRequired[str | None]
    workspace_id: NotRequired[str | None]


class RequestPaneSwapParams(TypedDict, total=False):
    direction: NotRequired[RequestPaneDirection | None]
    pane_id: NotRequired[str | None]
    source_pane_id: NotRequired[str | None]
    target_pane_id: NotRequired[str | None]


class RequestPaneTarget(TypedDict):
    pane_id: str


class RequestPaneTextPoint(TypedDict):
    col: int
    row: int


class RequestPaneTextRange(TypedDict):
    end: RequestPaneTextPoint
    start: RequestPaneTextPoint


class RequestPaneWaitForOutputParams(TypedDict, total=False):
    lines: NotRequired[int | None]
    match: Required[RequestOutputMatch]
    pane_id: Required[str]
    source: Required[RequestReadSource]
    strip_ansi: NotRequired[bool]
    timeout_ms: NotRequired[int | None]


type RequestPaneZoomMode = Literal["toggle", "on", "off"]


class RequestPaneZoomParams(TypedDict, total=False):
    mode: NotRequired[RequestPaneZoomMode]
    pane_id: NotRequired[str | None]


type RequestPingParams = JsonObject


class RequestPluginActionInvokeParams(TypedDict, total=False):
    action_id: Required[str]
    context: NotRequired[RequestPluginInvocationContext | None]
    plugin_id: NotRequired[str | None]


class RequestPluginActionListParams(TypedDict, total=False):
    plugin_id: NotRequired[str | None]


class RequestPluginInvocationContext(TypedDict, total=False):
    clicked_url: NotRequired[str | None]
    correlation_id: NotRequired[str | None]
    focused_pane_agent: NotRequired[str | None]
    focused_pane_cwd: NotRequired[str | None]
    focused_pane_id: NotRequired[str | None]
    focused_pane_status: NotRequired[RequestAgentStatus | None]
    invocation_source: NotRequired[str | None]
    link_handler_id: NotRequired[str | None]
    selected_text: NotRequired[str | None]
    tab_id: NotRequired[str | None]
    tab_label: NotRequired[str | None]
    workspace_cwd: NotRequired[str | None]
    workspace_id: NotRequired[str | None]
    workspace_label: NotRequired[str | None]
    worktree: NotRequired[RequestWorkspaceWorktreeInfo | None]


class RequestPluginLinkParams(TypedDict, total=False):
    enabled: NotRequired[bool]
    path: Required[str]
    source: NotRequired[RequestPluginSourceInfo | None]


class RequestPluginListParams(TypedDict, total=False):
    plugin_id: NotRequired[str | None]


class RequestPluginLogListParams(TypedDict, total=False):
    limit: NotRequired[int | None]
    plugin_id: NotRequired[str | None]


class RequestPluginPaneCloseParams(TypedDict):
    pane_id: str


class RequestPluginPaneFocusParams(TypedDict):
    pane_id: str


class RequestPluginPaneOpenParams(TypedDict, total=False):
    cwd: NotRequired[str | None]
    direction: NotRequired[RequestSplitDirection | None]
    entrypoint: Required[str]
    env: NotRequired[dict[str, str]]
    focus: NotRequired[bool]
    height: NotRequired[RequestPopupSize | None]
    placement: NotRequired[RequestPluginPanePlacement | None]
    plugin_id: Required[str]
    target_pane_id: NotRequired[str | None]
    width: NotRequired[RequestPopupSize | None]
    workspace_id: NotRequired[str | None]


type RequestPluginPanePlacement = Literal["overlay", "popup", "split", "tab", "zoomed"]


class RequestPluginSetEnabledParams(TypedDict):
    plugin_id: str


class RequestPluginSourceInfo(TypedDict, total=False):
    installed_unix_ms: NotRequired[int | None]
    kind: NotRequired[RequestPluginSourceKind]
    managed_path: NotRequired[str | None]
    owner: NotRequired[str | None]
    repo: NotRequired[str | None]
    requested_ref: NotRequired[str | None]
    resolved_commit: NotRequired[str | None]
    subdir: NotRequired[str | None]


type RequestPluginSourceKind = Literal["local", "github"]


class RequestPluginUnlinkParams(TypedDict):
    plugin_id: str


type RequestPopupSize = int | str


class RequestProductAnnouncementDismissParams(TypedDict):
    id: str
    version: str


type RequestReadFormat = Literal["text", "ansi"]


type RequestReadSource = Literal["visible", "recent", "recent_unwrapped", "detection"]


class RequestReleaseNotesDismissParams(TypedDict):
    version: str


class RequestServerLiveHandoffParams(TypedDict, total=False):
    expected_protocol: NotRequired[int | None]
    expected_version: NotRequired[str | None]
    import_exe: NotRequired[str | None]


type RequestSplitDirection = Literal["right", "down"]


class RequestSubscriptionVariant1(TypedDict):
    type: Literal["workspace.created"]


class RequestSubscriptionVariant2(TypedDict):
    type: Literal["workspace.updated"]


class RequestSubscriptionVariant3(TypedDict):
    type: Literal["workspace.metadata_updated"]


class RequestSubscriptionVariant4(TypedDict):
    type: Literal["workspace.renamed"]


class RequestSubscriptionVariant5(TypedDict):
    type: Literal["workspace.moved"]


class RequestSubscriptionVariant6(TypedDict):
    type: Literal["workspace.reordered"]


class RequestSubscriptionVariant7(TypedDict):
    type: Literal["workspace.closed"]


class RequestSubscriptionVariant8(TypedDict):
    type: Literal["workspace.focused"]


class RequestSubscriptionVariant9(TypedDict):
    type: Literal["worktree.created"]


class RequestSubscriptionVariant10(TypedDict):
    type: Literal["worktree.opened"]


class RequestSubscriptionVariant11(TypedDict):
    type: Literal["worktree.removed"]


class RequestSubscriptionVariant12(TypedDict):
    type: Literal["tab.created"]


class RequestSubscriptionVariant13(TypedDict):
    type: Literal["tab.closed"]


class RequestSubscriptionVariant14(TypedDict):
    type: Literal["tab.focused"]


class RequestSubscriptionVariant15(TypedDict):
    type: Literal["tab.renamed"]


class RequestSubscriptionVariant16(TypedDict):
    type: Literal["tab.moved"]


class RequestSubscriptionVariant17(TypedDict):
    type: Literal["pane.created"]


class RequestSubscriptionVariant18(TypedDict):
    type: Literal["pane.closed"]


class RequestSubscriptionVariant19(TypedDict):
    type: Literal["pane.updated"]


class RequestSubscriptionVariant20(TypedDict):
    type: Literal["pane.focused"]


class RequestSubscriptionVariant21(TypedDict):
    type: Literal["pane.moved"]


class RequestSubscriptionVariant22(TypedDict):
    type: Literal["pane.exited"]


class RequestSubscriptionVariant23(TypedDict):
    type: Literal["pane.agent_detected"]


class RequestSubscriptionVariant24(TypedDict, total=False):
    lines: NotRequired[int | None]
    match: Required[RequestOutputMatch]
    pane_id: Required[str]
    source: Required[RequestReadSource]
    strip_ansi: NotRequired[bool]
    type: Required[Literal["pane.output_matched"]]


class RequestSubscriptionVariant25(TypedDict, total=False):
    agent_status: NotRequired[RequestAgentStatus | None]
    pane_id: Required[str]
    type: Required[Literal["pane.agent_status_changed"]]


class RequestSubscriptionVariant26(TypedDict):
    pane_id: str
    type: Literal["pane.scroll_changed"]


class RequestSubscriptionVariant27(TypedDict):
    type: Literal["layout.updated"]


type RequestSubscription = (
    RequestSubscriptionVariant1
    | RequestSubscriptionVariant2
    | RequestSubscriptionVariant3
    | RequestSubscriptionVariant4
    | RequestSubscriptionVariant5
    | RequestSubscriptionVariant6
    | RequestSubscriptionVariant7
    | RequestSubscriptionVariant8
    | RequestSubscriptionVariant9
    | RequestSubscriptionVariant10
    | RequestSubscriptionVariant11
    | RequestSubscriptionVariant12
    | RequestSubscriptionVariant13
    | RequestSubscriptionVariant14
    | RequestSubscriptionVariant15
    | RequestSubscriptionVariant16
    | RequestSubscriptionVariant17
    | RequestSubscriptionVariant18
    | RequestSubscriptionVariant19
    | RequestSubscriptionVariant20
    | RequestSubscriptionVariant21
    | RequestSubscriptionVariant22
    | RequestSubscriptionVariant23
    | RequestSubscriptionVariant24
    | RequestSubscriptionVariant25
    | RequestSubscriptionVariant26
    | RequestSubscriptionVariant27
)


class RequestTabCreateParams(TypedDict, total=False):
    cwd: NotRequired[str | None]
    env: NotRequired[dict[str, str]]
    focus: NotRequired[bool]
    label: NotRequired[str | None]
    workspace_id: NotRequired[str | None]


class RequestTabListParams(TypedDict, total=False):
    workspace_id: NotRequired[str | None]


class RequestTabMoveParams(TypedDict):
    insert_index: int
    tab_id: str


class RequestTabRenameParams(TypedDict):
    label: str
    tab_id: str


class RequestTabTarget(TypedDict):
    tab_id: str


type RequestToastHerdrPosition = Literal[
    "top-left", "top-right", "bottom-left", "bottom-right"
]


class RequestWorkspaceCloseParams(TypedDict, total=False):
    close_group: NotRequired[bool]
    workspace_id: Required[str]


class RequestWorkspaceCreateParams(TypedDict, total=False):
    cwd: NotRequired[str | None]
    env: NotRequired[dict[str, str]]
    focus: NotRequired[bool]
    label: NotRequired[str | None]
    source_workspace_id: NotRequired[str | None]


class RequestWorkspaceMoveBlockParams(TypedDict, total=False):
    before_workspace_id: NotRequired[str | None]
    workspace_ids: Required[list[str]]


class RequestWorkspaceMoveParams(TypedDict):
    insert_index: int
    workspace_id: str


class RequestWorkspaceRenameParams(TypedDict):
    label: str
    workspace_id: str


class RequestWorkspaceReportMetadataParams(TypedDict, total=False):
    seq: NotRequired[int | None]
    source: Required[str]
    tokens: Required[dict[str, str | None]]
    ttl_ms: NotRequired[int | None]
    workspace_id: Required[str]


class RequestWorkspaceTarget(TypedDict):
    workspace_id: str


class RequestWorkspaceWorktreeInfo(TypedDict):
    checkout_path: str
    is_linked_worktree: bool
    repo_key: str
    repo_name: str
    repo_root: str


class RequestWorktreeCreateParams(TypedDict, total=False):
    base: NotRequired[str | None]
    branch: NotRequired[str | None]
    cwd: NotRequired[str | None]
    focus: NotRequired[bool]
    label: NotRequired[str | None]
    path: NotRequired[str | None]
    trust_repository: NotRequired[bool]
    workspace_id: NotRequired[str | None]


class RequestWorktreeListParams(TypedDict, total=False):
    cwd: NotRequired[str | None]
    trust_repository: NotRequired[bool]
    workspace_id: NotRequired[str | None]


class RequestWorktreeOpenParams(TypedDict, total=False):
    branch: NotRequired[str | None]
    cwd: NotRequired[str | None]
    focus: NotRequired[bool]
    label: NotRequired[str | None]
    path: NotRequired[str | None]
    trust_repository: NotRequired[bool]
    workspace_id: NotRequired[str | None]


class RequestWorktreeRemoveParams(TypedDict, total=False):
    force: NotRequired[bool]
    trust_repository: NotRequired[bool]
    workspace_id: Required[str]


# success_response definitions


class ResponseAgentInfo(TypedDict, total=False):
    agent: NotRequired[str | None]
    agent_session: NotRequired[ResponseAgentSessionInfo | None]
    agent_status: Required[ResponseAgentStatus]
    cwd: NotRequired[str | None]
    display_agent: NotRequired[str | None]
    focused: Required[bool]
    foreground_cwd: NotRequired[str | None]
    interactive_ready: NotRequired[bool]
    launch_pending: NotRequired[bool]
    name: NotRequired[str | None]
    pane_id: Required[str]
    revision: Required[int]
    screen_detection_skipped: NotRequired[bool]
    state_change_seq: NotRequired[int]
    state_labels: NotRequired[dict[str, str]]
    tab_id: Required[str]
    terminal_id: Required[str]
    terminal_title: NotRequired[str | None]
    terminal_title_stripped: NotRequired[str | None]
    title: NotRequired[str | None]
    tokens: NotRequired[dict[str, str]]
    workspace_id: Required[str]


class ResponseAgentManifestInfo(TypedDict, total=False):
    active_version: NotRequired[str | None]
    agent: Required[str]
    cached_remote_version: NotRequired[str | None]
    local_override_shadowing_remote: Required[bool]
    remote_last_checked_unix: NotRequired[int | None]
    remote_update_error: NotRequired[str | None]
    remote_update_result: NotRequired[str | None]
    source: Required[str]
    source_kind: Required[str]
    warning: NotRequired[str | None]


class ResponseAgentSessionInfo(TypedDict):
    agent: str
    kind: ResponseAgentSessionRefKind
    source: str
    value: str


type ResponseAgentSessionRefKind = Literal["id", "path"]


type ResponseAgentStatus = Literal["idle", "working", "blocked", "done", "unknown"]


type ResponseClientWindowTitleReason = Literal["set", "cleared", "no_foreground_client"]


type ResponseConfigReloadStatus = Literal["applied", "partial", "failed"]


class ResponseEventDataVariant1(TypedDict):
    type: Literal["workspace_created"]
    workspace: ResponseWorkspaceInfo


class ResponseEventDataVariant2(TypedDict):
    type: Literal["workspace_updated"]
    workspace: ResponseWorkspaceInfo


class ResponseEventDataVariant3(TypedDict):
    type: Literal["workspace_metadata_updated"]
    workspace: ResponseWorkspaceInfo


class ResponseEventDataVariant4(TypedDict, total=False):
    type: Required[Literal["workspace_closed"]]
    workspace: NotRequired[ResponseWorkspaceInfo | None]
    workspace_id: Required[str]


class ResponseEventDataVariant5(TypedDict):
    label: str
    type: Literal["workspace_renamed"]
    workspace_id: str


class ResponseEventDataVariant6(TypedDict):
    insert_index: int
    type: Literal["workspace_moved"]
    workspace_id: str
    workspaces: list[ResponseWorkspaceInfo]


class ResponseEventDataVariant7(TypedDict, total=False):
    before_workspace_id: NotRequired[str | None]
    type: Required[Literal["workspace_reordered"]]
    workspace_ids: Required[list[str]]
    workspaces: Required[list[ResponseWorkspaceInfo]]


class ResponseEventDataVariant8(TypedDict):
    type: Literal["workspace_focused"]
    workspace_id: str


class ResponseEventDataVariant9(TypedDict):
    type: Literal["worktree_created"]
    workspace: ResponseWorkspaceInfo
    worktree: ResponseWorktreeInfo


class ResponseEventDataVariant10(TypedDict):
    already_open: bool
    type: Literal["worktree_opened"]
    workspace: ResponseWorkspaceInfo
    worktree: ResponseWorktreeInfo


class ResponseEventDataVariant11(TypedDict, total=False):
    forced: Required[bool]
    type: Required[Literal["worktree_removed"]]
    workspace: NotRequired[ResponseWorkspaceInfo | None]
    workspace_id: Required[str]
    worktree: Required[ResponseWorktreeInfo]


class ResponseEventDataVariant12(TypedDict):
    tab: ResponseTabInfo
    type: Literal["tab_created"]


class ResponseEventDataVariant13(TypedDict):
    tab_id: str
    type: Literal["tab_closed"]
    workspace_id: str


class ResponseEventDataVariant14(TypedDict):
    label: str
    tab_id: str
    type: Literal["tab_renamed"]
    workspace_id: str


class ResponseEventDataVariant15(TypedDict):
    insert_index: int
    tab_id: str
    tabs: list[ResponseTabInfo]
    type: Literal["tab_moved"]
    workspace_id: str


class ResponseEventDataVariant16(TypedDict):
    tab_id: str
    type: Literal["tab_focused"]
    workspace_id: str


class ResponseEventDataVariant17(TypedDict):
    pane: ResponsePaneInfo
    type: Literal["pane_created"]


class ResponseEventDataVariant18(TypedDict):
    pane_id: str
    type: Literal["pane_closed"]
    workspace_id: str


class ResponseEventDataVariant19(TypedDict):
    pane: ResponsePaneInfo
    type: Literal["pane_updated"]


class ResponseEventDataVariant20(TypedDict):
    pane_id: str
    type: Literal["pane_focused"]
    workspace_id: str


class ResponseEventDataVariant21(TypedDict, total=False):
    closed_tab_id: NotRequired[str | None]
    closed_workspace_id: NotRequired[str | None]
    created_tab: NotRequired[ResponseTabInfo | None]
    created_workspace: NotRequired[ResponseWorkspaceInfo | None]
    pane: Required[ResponsePaneInfo]
    previous_pane_id: Required[str]
    previous_tab_id: Required[str]
    previous_workspace_id: Required[str]
    type: Required[Literal["pane_moved"]]


class ResponseEventDataVariant22(TypedDict):
    pane_id: str
    revision: int
    type: Literal["pane_output_changed"]
    workspace_id: str


class ResponseEventDataVariant23(TypedDict):
    pane_id: str
    type: Literal["pane_exited"]
    workspace_id: str


class ResponseEventDataVariant24(TypedDict, total=False):
    agent: NotRequired[str | None]
    final_status: NotRequired[ResponseAgentStatus | None]
    pane_id: Required[str]
    released: NotRequired[bool]
    type: Required[Literal["pane_agent_detected"]]
    workspace_id: Required[str]


class ResponseEventDataVariant25(TypedDict, total=False):
    agent: NotRequired[str | None]
    agent_status: Required[ResponseAgentStatus]
    display_agent: NotRequired[str | None]
    pane_id: Required[str]
    state_labels: NotRequired[dict[str, str]]
    title: NotRequired[str | None]
    type: Required[Literal["pane_agent_status_changed"]]
    workspace_id: Required[str]


class ResponseEventDataVariant26(TypedDict):
    layout: ResponsePaneLayoutSnapshot
    type: Literal["layout_updated"]


type ResponseEventData = (
    ResponseEventDataVariant1
    | ResponseEventDataVariant2
    | ResponseEventDataVariant3
    | ResponseEventDataVariant4
    | ResponseEventDataVariant5
    | ResponseEventDataVariant6
    | ResponseEventDataVariant7
    | ResponseEventDataVariant8
    | ResponseEventDataVariant9
    | ResponseEventDataVariant10
    | ResponseEventDataVariant11
    | ResponseEventDataVariant12
    | ResponseEventDataVariant13
    | ResponseEventDataVariant14
    | ResponseEventDataVariant15
    | ResponseEventDataVariant16
    | ResponseEventDataVariant17
    | ResponseEventDataVariant18
    | ResponseEventDataVariant19
    | ResponseEventDataVariant20
    | ResponseEventDataVariant21
    | ResponseEventDataVariant22
    | ResponseEventDataVariant23
    | ResponseEventDataVariant24
    | ResponseEventDataVariant25
    | ResponseEventDataVariant26
)


class ResponseEventEnvelope(TypedDict):
    data: ResponseEventData
    event: ResponseEventKind


type ResponseEventKind = Literal[
    "workspace_created",
    "workspace_updated",
    "workspace_metadata_updated",
    "workspace_closed",
    "workspace_renamed",
    "workspace_moved",
    "workspace_reordered",
    "workspace_focused",
    "worktree_created",
    "worktree_opened",
    "worktree_removed",
    "tab_created",
    "tab_closed",
    "tab_renamed",
    "tab_moved",
    "tab_focused",
    "pane_created",
    "pane_closed",
    "pane_updated",
    "pane_focused",
    "pane_moved",
    "pane_output_changed",
    "pane_exited",
    "pane_agent_detected",
    "pane_agent_status_changed",
    "layout_updated",
]


class ResponseInstalledPluginInfo(TypedDict, total=False):
    actions: NotRequired[list[ResponsePluginManifestAction]]
    build: NotRequired[list[ResponsePluginManifestBuild]]
    description: NotRequired[str | None]
    enabled: Required[bool]
    events: NotRequired[list[ResponsePluginManifestEventHook]]
    link_handlers: NotRequired[list[ResponsePluginManifestLinkHandler]]
    manifest_path: Required[str]
    min_herdr_version: NotRequired[str]
    name: Required[str]
    panes: NotRequired[list[ResponsePluginManifestPane]]
    platforms: NotRequired[list[JsonObject] | None]
    plugin_id: Required[str]
    plugin_root: Required[str]
    source: NotRequired[ResponsePluginSourceInfo]
    startup: NotRequired[list[ResponsePluginManifestStartup]]
    version: Required[str]
    warnings: NotRequired[list[str]]


class ResponseIntegrationInfo(TypedDict):
    available: bool
    command: str
    label: str
    state: ResponseIntegrationState
    target: ResponseIntegrationTarget


class ResponseIntegrationInstallResult(TypedDict):
    messages: list[str]


type ResponseIntegrationState = Literal["not_installed", "current", "outdated"]


type ResponseIntegrationTarget = Literal[
    "pi",
    "omp",
    "claude",
    "codex",
    "copilot",
    "devin",
    "droid",
    "kimi",
    "opencode",
    "kilo",
    "hermes",
    "qodercli",
    "qwen",
    "cursor",
    "mastracode",
    "antigravity_cli",
    "grok",
]


class ResponseIntegrationUninstallResult(TypedDict):
    messages: list[str]


class ResponseLayoutDescription(TypedDict):
    focused_pane_id: str
    root: ResponseLayoutNode
    tab_id: str
    workspace_id: str
    zoomed: bool


class ResponseLayoutNodeVariant1(TypedDict, total=False):
    command: NotRequired[list[JsonObject] | None]
    cwd: NotRequired[str | None]
    env: NotRequired[dict[str, str]]
    label: NotRequired[str | None]
    pane_id: NotRequired[str | None]
    type: Required[Literal["pane"]]


class ResponseLayoutNodeVariant2(TypedDict):
    direction: ResponseSplitDirection
    first: ResponseLayoutNode
    ratio: int
    second: ResponseLayoutNode
    type: Literal["split"]


type ResponseLayoutNode = ResponseLayoutNodeVariant1 | ResponseLayoutNodeVariant2


type ResponseNotificationShowReason = Literal[
    "shown", "disabled", "rate_limited", "no_foreground_client", "busy"
]


type ResponsePaneDirection = Literal["left", "right", "up", "down"]


class ResponsePaneEdgesResult(TypedDict):
    down: bool
    layout: ResponsePaneLayoutSnapshot
    left: bool
    pane_id: str
    right: bool
    up: bool


type ResponsePaneFocusDirectionReason = Literal["no_neighbor"]


class ResponsePaneFocusDirectionResult(TypedDict, total=False):
    changed: Required[bool]
    focused_pane_id: NotRequired[str | None]
    layout: Required[ResponsePaneLayoutSnapshot]
    reason: NotRequired[ResponsePaneFocusDirectionReason | None]
    source_pane_id: Required[str]


class ResponsePaneInfo(TypedDict, total=False):
    agent: NotRequired[str | None]
    agent_session: NotRequired[ResponseAgentSessionInfo | None]
    agent_status: Required[ResponseAgentStatus]
    cwd: NotRequired[str | None]
    display_agent: NotRequired[str | None]
    focused: Required[bool]
    foreground_cwd: NotRequired[str | None]
    label: NotRequired[str | None]
    pane_id: Required[str]
    revision: Required[int]
    scroll: NotRequired[ResponsePaneScrollInfo | None]
    state_labels: NotRequired[dict[str, str]]
    tab_id: Required[str]
    terminal_id: Required[str]
    terminal_title: NotRequired[str | None]
    terminal_title_stripped: NotRequired[str | None]
    title: NotRequired[str | None]
    tokens: NotRequired[dict[str, str]]
    workspace_id: Required[str]


class ResponsePaneLayoutPane(TypedDict):
    focused: bool
    pane_id: str
    rect: ResponsePaneLayoutRect


class ResponsePaneLayoutRect(TypedDict):
    height: int
    width: int
    x: int
    y: int


class ResponsePaneLayoutSnapshot(TypedDict):
    area: ResponsePaneLayoutRect
    focused_pane_id: str
    panes: list[ResponsePaneLayoutPane]
    splits: list[ResponsePaneLayoutSplit]
    tab_id: str
    workspace_id: str
    zoomed: bool


class ResponsePaneLayoutSplit(TypedDict):
    direction: ResponseSplitDirection
    id: str
    ratio: int
    rect: ResponsePaneLayoutRect


class ResponsePaneLinkRegion(TypedDict):
    end_col: int
    row: int
    start_col: int


type ResponsePaneMoveReason = Literal["same_tab", "zoomed_tab"]


class ResponsePaneMoveResult(TypedDict, total=False):
    changed: Required[bool]
    closed_tab_id: NotRequired[str | None]
    closed_workspace_id: NotRequired[str | None]
    created_tab: NotRequired[ResponseTabInfo | None]
    created_workspace: NotRequired[ResponseWorkspaceInfo | None]
    focused_pane_id: Required[str]
    pane: Required[ResponsePaneInfo]
    previous_pane_id: Required[str]
    previous_tab_id: Required[str]
    previous_workspace_id: Required[str]
    reason: NotRequired[ResponsePaneMoveReason | None]
    source_layout: NotRequired[ResponsePaneLayoutSnapshot | None]
    target_layout: Required[ResponsePaneLayoutSnapshot]


class ResponsePaneNeighborResult(TypedDict, total=False):
    direction: Required[ResponsePaneDirection]
    layout: Required[ResponsePaneLayoutSnapshot]
    neighbor_pane_id: NotRequired[str | None]
    pane_id: Required[str]


class ResponsePaneProcessInfo(TypedDict, total=False):
    foreground_process_group_id: NotRequired[int | None]
    foreground_processes: NotRequired[list[ResponsePaneProcessInfoProcess]]
    pane_id: Required[str]
    shell_pid: NotRequired[int | None]
    tty: NotRequired[str | None]


class ResponsePaneProcessInfoProcess(TypedDict, total=False):
    argv: NotRequired[list[JsonObject] | None]
    argv0: NotRequired[str | None]
    cmdline: NotRequired[str | None]
    cwd: NotRequired[str | None]
    name: Required[str]
    pid: Required[int]


class ResponsePaneReadResult(TypedDict):
    format: ResponseReadFormat
    pane_id: str
    revision: int
    source: ResponseReadSource
    tab_id: str
    text: str
    truncated: bool
    workspace_id: str


type ResponsePaneResizeReason = Literal["unchanged"]


class ResponsePaneResizeResult(TypedDict, total=False):
    changed: Required[bool]
    focused_pane_id: Required[str]
    layout: Required[ResponsePaneLayoutSnapshot]
    pane_id: Required[str]
    reason: NotRequired[ResponsePaneResizeReason | None]


class ResponsePaneScrollInfo(TypedDict):
    max_offset_from_bottom: int
    offset_from_bottom: int
    viewport_rows: int


type ResponsePaneSwapReason = Literal[
    "no_neighbor", "same_pane", "not_found", "cross_tab"
]


class ResponsePaneSwapResult(TypedDict, total=False):
    changed: Required[bool]
    focused_pane_id: Required[str]
    layout: Required[ResponsePaneLayoutSnapshot]
    reason: NotRequired[ResponsePaneSwapReason | None]
    source_pane_id: Required[str]
    target_pane_id: NotRequired[str | None]


class ResponsePaneTextPoint(TypedDict):
    col: int
    row: int


class ResponsePaneTextRange(TypedDict):
    end: ResponsePaneTextPoint
    start: ResponsePaneTextPoint


type ResponsePaneZoomReason = Literal[
    "single_pane", "already_zoomed", "already_unzoomed"
]


class ResponsePaneZoomResult(TypedDict, total=False):
    changed: Required[bool]
    focus_changed: Required[bool]
    focused_pane_id: Required[str]
    layout: Required[ResponsePaneLayoutSnapshot]
    pane_id: Required[str]
    reason: NotRequired[ResponsePaneZoomReason | None]
    zoom_changed: Required[bool]
    zoomed: Required[bool]


type ResponsePluginActionContext = Literal[
    "global", "workspace", "tab", "pane", "selection"
]


class ResponsePluginActionInfo(TypedDict, total=False):
    action_id: Required[str]
    command: Required[list[str]]
    contexts: NotRequired[list[ResponsePluginActionContext]]
    description: NotRequired[str | None]
    platforms: NotRequired[list[JsonObject] | None]
    plugin_id: Required[str]
    title: Required[str]


class ResponsePluginCommandLogInfo(TypedDict, total=False):
    action_id: NotRequired[str | None]
    command: Required[list[str]]
    error: NotRequired[str | None]
    event: NotRequired[str | None]
    exit_code: NotRequired[int | None]
    finished_unix_ms: NotRequired[int | None]
    log_id: Required[str]
    plugin_id: Required[str]
    started_unix_ms: Required[int]
    status: Required[ResponsePluginCommandStatus]
    stderr: NotRequired[str | None]
    stdout: NotRequired[str | None]


type ResponsePluginCommandStatus = Literal["running", "succeeded", "failed"]


class ResponsePluginInvocationContext(TypedDict, total=False):
    clicked_url: NotRequired[str | None]
    correlation_id: NotRequired[str | None]
    focused_pane_agent: NotRequired[str | None]
    focused_pane_cwd: NotRequired[str | None]
    focused_pane_id: NotRequired[str | None]
    focused_pane_status: NotRequired[ResponseAgentStatus | None]
    invocation_source: NotRequired[str | None]
    link_handler_id: NotRequired[str | None]
    selected_text: NotRequired[str | None]
    tab_id: NotRequired[str | None]
    tab_label: NotRequired[str | None]
    workspace_cwd: NotRequired[str | None]
    workspace_id: NotRequired[str | None]
    workspace_label: NotRequired[str | None]
    worktree: NotRequired[ResponseWorkspaceWorktreeInfo | None]


class ResponsePluginManifestAction(TypedDict, total=False):
    command: Required[list[str]]
    contexts: NotRequired[list[ResponsePluginActionContext]]
    description: NotRequired[str | None]
    id: Required[str]
    platforms: NotRequired[list[JsonObject] | None]
    title: Required[str]


class ResponsePluginManifestBuild(TypedDict, total=False):
    command: Required[list[str]]
    platforms: NotRequired[list[JsonObject] | None]


class ResponsePluginManifestEventHook(TypedDict, total=False):
    command: Required[list[str]]
    on: Required[str]
    platforms: NotRequired[list[JsonObject] | None]


class ResponsePluginManifestLinkHandler(TypedDict, total=False):
    action: Required[str]
    id: Required[str]
    pattern: Required[str]
    platforms: NotRequired[list[JsonObject] | None]
    title: Required[str]


class ResponsePluginManifestPane(TypedDict, total=False):
    command: Required[list[str]]
    description: NotRequired[str | None]
    height: NotRequired[ResponsePopupSize | None]
    id: Required[str]
    placement: NotRequired[ResponsePluginPanePlacement]
    platforms: NotRequired[list[JsonObject] | None]
    title: Required[str]
    width: NotRequired[ResponsePopupSize | None]


class ResponsePluginManifestStartup(TypedDict, total=False):
    command: Required[list[str]]
    platforms: NotRequired[list[JsonObject] | None]


class ResponsePluginPaneInfo(TypedDict):
    entrypoint: str
    pane: ResponsePaneInfo
    plugin_id: str


type ResponsePluginPanePlacement = Literal["overlay", "popup", "split", "tab", "zoomed"]


type ResponsePluginPlatform = Literal["linux", "macos", "windows"]


class ResponsePluginSourceInfo(TypedDict, total=False):
    installed_unix_ms: NotRequired[int | None]
    kind: NotRequired[ResponsePluginSourceKind]
    managed_path: NotRequired[str | None]
    owner: NotRequired[str | None]
    repo: NotRequired[str | None]
    requested_ref: NotRequired[str | None]
    resolved_commit: NotRequired[str | None]
    subdir: NotRequired[str | None]


type ResponsePluginSourceKind = Literal["local", "github"]


type ResponsePopupSize = int | str


type ResponseReadFormat = Literal["text", "ansi"]


type ResponseReadSource = Literal["visible", "recent", "recent_unwrapped", "detection"]


class ResponseResponseResultVariant1(TypedDict, total=False):
    capabilities: NotRequired[ResponseServerCapabilities | None]
    protocol: Required[int]
    type: Required[Literal["pong"]]
    version: Required[str]


class ResponseResponseResultVariant2(TypedDict):
    snapshot: ResponseSessionSnapshot
    type: Literal["session_snapshot"]


class ResponseResponseResultVariant3(TypedDict):
    type: Literal["workspace_info"]
    workspace: ResponseWorkspaceInfo


class ResponseResponseResultVariant4(TypedDict):
    root_pane: ResponsePaneInfo
    tab: ResponseTabInfo
    type: Literal["workspace_created"]
    workspace: ResponseWorkspaceInfo


class ResponseResponseResultVariant5(TypedDict):
    type: Literal["workspace_list"]
    workspaces: list[ResponseWorkspaceInfo]


class ResponseResponseResultVariant6(TypedDict):
    source: ResponseWorktreeSourceInfo
    type: Literal["worktree_list"]
    worktrees: list[ResponseWorktreeInfo]


class ResponseResponseResultVariant7(TypedDict):
    root_pane: ResponsePaneInfo
    tab: ResponseTabInfo
    type: Literal["worktree_created"]
    workspace: ResponseWorkspaceInfo
    worktree: ResponseWorktreeInfo


class ResponseResponseResultVariant8(TypedDict):
    already_open: bool
    root_pane: ResponsePaneInfo
    tab: ResponseTabInfo
    type: Literal["worktree_opened"]
    workspace: ResponseWorkspaceInfo
    worktree: ResponseWorktreeInfo


class ResponseResponseResultVariant9(TypedDict):
    forced: bool
    path: str
    type: Literal["worktree_removed"]
    workspace_id: str


class ResponseResponseResultVariant10(TypedDict):
    tab: ResponseTabInfo
    type: Literal["tab_info"]


class ResponseResponseResultVariant11(TypedDict):
    root_pane: ResponsePaneInfo
    tab: ResponseTabInfo
    type: Literal["tab_created"]


class ResponseResponseResultVariant12(TypedDict):
    tabs: list[ResponseTabInfo]
    type: Literal["tab_list"]


class ResponseResponseResultVariant13(TypedDict):
    agent: ResponseAgentInfo
    type: Literal["agent_info"]


class ResponseResponseResultVariant14(TypedDict):
    agent: ResponseAgentInfo
    argv: list[str]
    type: Literal["agent_started"]


class ResponseResponseResultVariant15(TypedDict):
    agent: ResponseAgentInfo
    type: Literal["agent_prompted"]


class ResponseResponseResultVariant16(TypedDict):
    agents: list[ResponseAgentInfo]
    type: Literal["agent_list"]


class ResponseResponseResultVariant17(TypedDict, total=False):
    active: Required[bool]
    label: NotRequired[str | None]
    source: NotRequired[str | None]
    type: Required[Literal["agent_view"]]


class ResponseResponseResultVariant18(TypedDict):
    pane: ResponsePaneInfo
    type: Literal["pane_info"]


class ResponseResponseResultVariant19(TypedDict):
    panes: list[ResponsePaneInfo]
    type: Literal["pane_list"]


class ResponseResponseResultVariant20(TypedDict):
    pane: ResponsePaneInfo
    type: Literal["pane_current"]


class ResponseResponseResultVariant21(TypedDict):
    swap: ResponsePaneSwapResult
    type: Literal["pane_swap"]


class ResponseResponseResultVariant22(TypedDict):
    move_result: ResponsePaneMoveResult
    type: Literal["pane_move"]


class ResponseResponseResultVariant23(TypedDict):
    type: Literal["pane_zoom"]
    zoom: ResponsePaneZoomResult


class ResponseResponseResultVariant24(TypedDict):
    layout: ResponsePaneLayoutSnapshot
    type: Literal["pane_layout"]


class ResponseResponseResultVariant25(TypedDict):
    process_info: ResponsePaneProcessInfo
    type: Literal["pane_process_info"]


class ResponseResponseResultVariant26(TypedDict):
    layout: ResponseLayoutDescription
    type: Literal["layout_export"]


class ResponseResponseResultVariant27(TypedDict):
    layout: ResponseLayoutDescription
    type: Literal["layout_apply"]


class ResponseResponseResultVariant28(TypedDict):
    layout: ResponseLayoutDescription
    type: Literal["layout_split_ratio_set"]


class ResponseResponseResultVariant29(TypedDict):
    neighbor: ResponsePaneNeighborResult
    type: Literal["pane_neighbor"]


class ResponseResponseResultVariant30(TypedDict):
    edges: ResponsePaneEdgesResult
    type: Literal["pane_edges"]


class ResponseResponseResultVariant31(TypedDict):
    focus: ResponsePaneFocusDirectionResult
    type: Literal["pane_focus_direction"]


class ResponseResponseResultVariant32(TypedDict):
    resize: ResponsePaneResizeResult
    type: Literal["pane_resize"]


class ResponseResponseResultVariant33(TypedDict):
    read: ResponsePaneReadResult
    type: Literal["pane_read"]


class ResponseResponseResultVariant34(TypedDict):
    pane_id: str
    text: str
    type: Literal["pane_selection"]


class ResponseResponseResultVariant35(TypedDict):
    content_revision: int
    cursor: ResponsePaneTextPoint
    pane_id: str
    type: Literal["pane_copy_motion"]


class ResponseResponseResultVariant36(TypedDict, total=False):
    content_revision: Required[int]
    current: NotRequired[int | None]
    current_global: NotRequired[int | None]
    matches: Required[list[ResponsePaneTextRange]]
    pane_id: Required[str]
    total: Required[int]
    type: Required[Literal["pane_copy_search"]]


class ResponseResponseResultVariant37(TypedDict):
    revision: int
    sequence: int
    type: Literal["pane_graphics_frame_ack"]


class ResponseResponseResultVariant38(TypedDict, total=False):
    cell_height_px: Required[int]
    cell_width_px: Required[int]
    file_frame_damage: NotRequired[bool]
    file_frame_direct_max_bytes: NotRequired[int | None]
    file_frame_directory: NotRequired[str | None]
    file_frame_formats: NotRequired[list[str]]
    file_frame_max_bytes: NotRequired[int | None]
    file_frame_transport: NotRequired[str | None]
    max_layers_per_pane: NotRequired[int]
    pane_visible: Required[bool]
    pixel_mouse: NotRequired[bool]
    type: Required[Literal["pane_graphics_info"]]


class ResponseResponseResultVariant39(TypedDict):
    explain: JSONValue
    type: Literal["agent_explain"]


class ResponseResponseResultVariant40(TypedDict):
    type: Literal["subscription_started"]


class ResponseResponseResultVariant41(TypedDict):
    event: ResponseEventEnvelope
    type: Literal["wait_matched"]


class ResponseResponseResultVariant42(TypedDict, total=False):
    matched_line: NotRequired[str | None]
    pane_id: Required[str]
    read: Required[ResponsePaneReadResult]
    revision: Required[int]
    type: Required[Literal["output_matched"]]


class ResponseResponseResultVariant43(TypedDict):
    reason: ResponseNotificationShowReason
    shown: bool
    type: Literal["notification_show"]


class ResponseResponseResultVariant44(TypedDict):
    changed: bool
    reason: ResponseClientWindowTitleReason
    type: Literal["client_window_title"]


class ResponseResponseResultVariant45(TypedDict):
    integrations: list[ResponseIntegrationInfo]
    type: Literal["integration_list"]


class ResponseResponseResultVariant46(TypedDict):
    details: ResponseIntegrationInstallResult
    target: ResponseIntegrationTarget
    type: Literal["integration_install"]


class ResponseResponseResultVariant47(TypedDict):
    details: ResponseIntegrationUninstallResult
    target: ResponseIntegrationTarget
    type: Literal["integration_uninstall"]


class ResponseResponseResultVariant48(TypedDict):
    manifests: list[ResponseAgentManifestInfo]
    type: Literal["agent_manifest_reload"]


class ResponseResponseResultVariant49(TypedDict, total=False):
    last_check_unix: NotRequired[int | None]
    last_result: NotRequired[str | None]
    manifests: Required[list[ResponseAgentManifestInfo]]
    type: Required[Literal["agent_manifest_status"]]


class ResponseResponseResultVariant50(TypedDict):
    plugin: ResponseInstalledPluginInfo
    type: Literal["plugin_linked"]


class ResponseResponseResultVariant51(TypedDict):
    plugins: list[ResponseInstalledPluginInfo]
    type: Literal["plugin_list"]


class ResponseResponseResultVariant52(TypedDict):
    plugin_id: str
    removed: bool
    type: Literal["plugin_unlinked"]


class ResponseResponseResultVariant53(TypedDict):
    plugin: ResponseInstalledPluginInfo
    type: Literal["plugin_enabled"]


class ResponseResponseResultVariant54(TypedDict):
    plugin: ResponseInstalledPluginInfo
    type: Literal["plugin_disabled"]


class ResponseResponseResultVariant55(TypedDict):
    actions: list[ResponsePluginActionInfo]
    type: Literal["plugin_action_list"]


class ResponseResponseResultVariant56(TypedDict):
    action: ResponsePluginActionInfo
    context: ResponsePluginInvocationContext
    log: ResponsePluginCommandLogInfo
    type: Literal["plugin_action_invoked"]


class ResponseResponseResultVariant57(TypedDict):
    regions: list[ResponsePaneLinkRegion]
    type: Literal["pane_link_resolved"]


class ResponseResponseResultVariant58(TypedDict, total=False):
    handled: Required[bool]
    type: Required[Literal["pane_link_activated"]]
    url: NotRequired[str | None]


class ResponseResponseResultVariant59(TypedDict):
    logs: list[ResponsePluginCommandLogInfo]
    type: Literal["plugin_log_list"]


class ResponseResponseResultVariant60(TypedDict):
    plugin_pane: ResponsePluginPaneInfo
    type: Literal["plugin_pane_opened"]


class ResponseResponseResultVariant61(TypedDict):
    plugin_pane: ResponsePluginPaneInfo
    type: Literal["plugin_pane_focused"]


class ResponseResponseResultVariant62(TypedDict):
    pane_id: str
    type: Literal["plugin_pane_closed"]


class ResponseResponseResultVariant63(TypedDict):
    diagnostics: list[str]
    status: ResponseConfigReloadStatus
    type: Literal["config_reload"]


class ResponseResponseResultVariant64(TypedDict):
    active: bool
    projection_revision: int
    type: Literal["client_shell_surface_set"]


class ResponseResponseResultVariant65(TypedDict):
    type: Literal["ok"]


type ResponseResponseResult = (
    ResponseResponseResultVariant1
    | ResponseResponseResultVariant2
    | ResponseResponseResultVariant3
    | ResponseResponseResultVariant4
    | ResponseResponseResultVariant5
    | ResponseResponseResultVariant6
    | ResponseResponseResultVariant7
    | ResponseResponseResultVariant8
    | ResponseResponseResultVariant9
    | ResponseResponseResultVariant10
    | ResponseResponseResultVariant11
    | ResponseResponseResultVariant12
    | ResponseResponseResultVariant13
    | ResponseResponseResultVariant14
    | ResponseResponseResultVariant15
    | ResponseResponseResultVariant16
    | ResponseResponseResultVariant17
    | ResponseResponseResultVariant18
    | ResponseResponseResultVariant19
    | ResponseResponseResultVariant20
    | ResponseResponseResultVariant21
    | ResponseResponseResultVariant22
    | ResponseResponseResultVariant23
    | ResponseResponseResultVariant24
    | ResponseResponseResultVariant25
    | ResponseResponseResultVariant26
    | ResponseResponseResultVariant27
    | ResponseResponseResultVariant28
    | ResponseResponseResultVariant29
    | ResponseResponseResultVariant30
    | ResponseResponseResultVariant31
    | ResponseResponseResultVariant32
    | ResponseResponseResultVariant33
    | ResponseResponseResultVariant34
    | ResponseResponseResultVariant35
    | ResponseResponseResultVariant36
    | ResponseResponseResultVariant37
    | ResponseResponseResultVariant38
    | ResponseResponseResultVariant39
    | ResponseResponseResultVariant40
    | ResponseResponseResultVariant41
    | ResponseResponseResultVariant42
    | ResponseResponseResultVariant43
    | ResponseResponseResultVariant44
    | ResponseResponseResultVariant45
    | ResponseResponseResultVariant46
    | ResponseResponseResultVariant47
    | ResponseResponseResultVariant48
    | ResponseResponseResultVariant49
    | ResponseResponseResultVariant50
    | ResponseResponseResultVariant51
    | ResponseResponseResultVariant52
    | ResponseResponseResultVariant53
    | ResponseResponseResultVariant54
    | ResponseResponseResultVariant55
    | ResponseResponseResultVariant56
    | ResponseResponseResultVariant57
    | ResponseResponseResultVariant58
    | ResponseResponseResultVariant59
    | ResponseResponseResultVariant60
    | ResponseResponseResultVariant61
    | ResponseResponseResultVariant62
    | ResponseResponseResultVariant63
    | ResponseResponseResultVariant64
    | ResponseResponseResultVariant65
)


class ResponseServerCapabilities(TypedDict, total=False):
    detached_server_daemon: NotRequired[bool]
    endpoint_protocol_generation: NotRequired[int | None]
    health_check: NotRequired[bool]
    live_handoff: Required[bool]
    surface_interest: NotRequired[bool]


class ResponseSessionSnapshot(TypedDict, total=False):
    agents: Required[list[ResponseAgentInfo]]
    focused_pane_id: NotRequired[str | None]
    focused_tab_id: NotRequired[str | None]
    focused_workspace_id: NotRequired[str | None]
    layouts: Required[list[ResponsePaneLayoutSnapshot]]
    panes: Required[list[ResponsePaneInfo]]
    protocol: Required[int]
    tabs: Required[list[ResponseTabInfo]]
    version: Required[str]
    workspaces: Required[list[ResponseWorkspaceInfo]]


type ResponseSplitDirection = Literal["right", "down"]


class ResponseTabInfo(TypedDict):
    agent_status: ResponseAgentStatus
    focused: bool
    label: str
    number: int
    pane_count: int
    tab_id: str
    workspace_id: str


class ResponseWorkspaceInfo(TypedDict, total=False):
    active_tab_id: Required[str]
    agent_status: Required[ResponseAgentStatus]
    focused: Required[bool]
    label: Required[str]
    number: Required[int]
    pane_count: Required[int]
    tab_count: Required[int]
    tokens: NotRequired[dict[str, str]]
    workspace_id: Required[str]
    worktree: NotRequired[ResponseWorkspaceWorktreeInfo | None]


class ResponseWorkspaceWorktreeInfo(TypedDict):
    checkout_path: str
    is_linked_worktree: bool
    repo_key: str
    repo_name: str
    repo_root: str


class ResponseWorktreeInfo(TypedDict, total=False):
    branch: NotRequired[str | None]
    is_bare: Required[bool]
    is_detached: Required[bool]
    is_linked_worktree: Required[bool]
    is_prunable: Required[bool]
    label: Required[str]
    open_workspace_id: NotRequired[str | None]
    path: Required[str]


class ResponseWorktreeSourceInfo(TypedDict, total=False):
    repo_key: Required[str]
    repo_name: Required[str]
    repo_root: Required[str]
    source_checkout_path: Required[str]
    source_workspace_id: NotRequired[str | None]


# error_response definitions


class ErrorErrorBody(TypedDict):
    code: str
    message: str


# event definitions


class EventAgentSessionInfo(TypedDict):
    agent: str
    kind: EventAgentSessionRefKind
    source: str
    value: str


type EventAgentSessionRefKind = Literal["id", "path"]


type EventAgentStatus = Literal["idle", "working", "blocked", "done", "unknown"]


class EventEventDataVariant1(TypedDict):
    type: Literal["workspace_created"]
    workspace: EventWorkspaceInfo


class EventEventDataVariant2(TypedDict):
    type: Literal["workspace_updated"]
    workspace: EventWorkspaceInfo


class EventEventDataVariant3(TypedDict):
    type: Literal["workspace_metadata_updated"]
    workspace: EventWorkspaceInfo


class EventEventDataVariant4(TypedDict, total=False):
    type: Required[Literal["workspace_closed"]]
    workspace: NotRequired[EventWorkspaceInfo | None]
    workspace_id: Required[str]


class EventEventDataVariant5(TypedDict):
    label: str
    type: Literal["workspace_renamed"]
    workspace_id: str


class EventEventDataVariant6(TypedDict):
    insert_index: int
    type: Literal["workspace_moved"]
    workspace_id: str
    workspaces: list[EventWorkspaceInfo]


class EventEventDataVariant7(TypedDict, total=False):
    before_workspace_id: NotRequired[str | None]
    type: Required[Literal["workspace_reordered"]]
    workspace_ids: Required[list[str]]
    workspaces: Required[list[EventWorkspaceInfo]]


class EventEventDataVariant8(TypedDict):
    type: Literal["workspace_focused"]
    workspace_id: str


class EventEventDataVariant9(TypedDict):
    type: Literal["worktree_created"]
    workspace: EventWorkspaceInfo
    worktree: EventWorktreeInfo


class EventEventDataVariant10(TypedDict):
    already_open: bool
    type: Literal["worktree_opened"]
    workspace: EventWorkspaceInfo
    worktree: EventWorktreeInfo


class EventEventDataVariant11(TypedDict, total=False):
    forced: Required[bool]
    type: Required[Literal["worktree_removed"]]
    workspace: NotRequired[EventWorkspaceInfo | None]
    workspace_id: Required[str]
    worktree: Required[EventWorktreeInfo]


class EventEventDataVariant12(TypedDict):
    tab: EventTabInfo
    type: Literal["tab_created"]


class EventEventDataVariant13(TypedDict):
    tab_id: str
    type: Literal["tab_closed"]
    workspace_id: str


class EventEventDataVariant14(TypedDict):
    label: str
    tab_id: str
    type: Literal["tab_renamed"]
    workspace_id: str


class EventEventDataVariant15(TypedDict):
    insert_index: int
    tab_id: str
    tabs: list[EventTabInfo]
    type: Literal["tab_moved"]
    workspace_id: str


class EventEventDataVariant16(TypedDict):
    tab_id: str
    type: Literal["tab_focused"]
    workspace_id: str


class EventEventDataVariant17(TypedDict):
    pane: EventPaneInfo
    type: Literal["pane_created"]


class EventEventDataVariant18(TypedDict):
    pane_id: str
    type: Literal["pane_closed"]
    workspace_id: str


class EventEventDataVariant19(TypedDict):
    pane: EventPaneInfo
    type: Literal["pane_updated"]


class EventEventDataVariant20(TypedDict):
    pane_id: str
    type: Literal["pane_focused"]
    workspace_id: str


class EventEventDataVariant21(TypedDict, total=False):
    closed_tab_id: NotRequired[str | None]
    closed_workspace_id: NotRequired[str | None]
    created_tab: NotRequired[EventTabInfo | None]
    created_workspace: NotRequired[EventWorkspaceInfo | None]
    pane: Required[EventPaneInfo]
    previous_pane_id: Required[str]
    previous_tab_id: Required[str]
    previous_workspace_id: Required[str]
    type: Required[Literal["pane_moved"]]


class EventEventDataVariant22(TypedDict):
    pane_id: str
    revision: int
    type: Literal["pane_output_changed"]
    workspace_id: str


class EventEventDataVariant23(TypedDict):
    pane_id: str
    type: Literal["pane_exited"]
    workspace_id: str


class EventEventDataVariant24(TypedDict, total=False):
    agent: NotRequired[str | None]
    final_status: NotRequired[EventAgentStatus | None]
    pane_id: Required[str]
    released: NotRequired[bool]
    type: Required[Literal["pane_agent_detected"]]
    workspace_id: Required[str]


class EventEventDataVariant25(TypedDict, total=False):
    agent: NotRequired[str | None]
    agent_status: Required[EventAgentStatus]
    display_agent: NotRequired[str | None]
    pane_id: Required[str]
    state_labels: NotRequired[dict[str, str]]
    title: NotRequired[str | None]
    type: Required[Literal["pane_agent_status_changed"]]
    workspace_id: Required[str]


class EventEventDataVariant26(TypedDict):
    layout: EventPaneLayoutSnapshot
    type: Literal["layout_updated"]


type EventEventData = (
    EventEventDataVariant1
    | EventEventDataVariant2
    | EventEventDataVariant3
    | EventEventDataVariant4
    | EventEventDataVariant5
    | EventEventDataVariant6
    | EventEventDataVariant7
    | EventEventDataVariant8
    | EventEventDataVariant9
    | EventEventDataVariant10
    | EventEventDataVariant11
    | EventEventDataVariant12
    | EventEventDataVariant13
    | EventEventDataVariant14
    | EventEventDataVariant15
    | EventEventDataVariant16
    | EventEventDataVariant17
    | EventEventDataVariant18
    | EventEventDataVariant19
    | EventEventDataVariant20
    | EventEventDataVariant21
    | EventEventDataVariant22
    | EventEventDataVariant23
    | EventEventDataVariant24
    | EventEventDataVariant25
    | EventEventDataVariant26
)


type EventEventKind = Literal[
    "workspace_created",
    "workspace_updated",
    "workspace_metadata_updated",
    "workspace_closed",
    "workspace_renamed",
    "workspace_moved",
    "workspace_reordered",
    "workspace_focused",
    "worktree_created",
    "worktree_opened",
    "worktree_removed",
    "tab_created",
    "tab_closed",
    "tab_renamed",
    "tab_moved",
    "tab_focused",
    "pane_created",
    "pane_closed",
    "pane_updated",
    "pane_focused",
    "pane_moved",
    "pane_output_changed",
    "pane_exited",
    "pane_agent_detected",
    "pane_agent_status_changed",
    "layout_updated",
]


class EventPaneInfo(TypedDict, total=False):
    agent: NotRequired[str | None]
    agent_session: NotRequired[EventAgentSessionInfo | None]
    agent_status: Required[EventAgentStatus]
    cwd: NotRequired[str | None]
    display_agent: NotRequired[str | None]
    focused: Required[bool]
    foreground_cwd: NotRequired[str | None]
    label: NotRequired[str | None]
    pane_id: Required[str]
    revision: Required[int]
    scroll: NotRequired[EventPaneScrollInfo | None]
    state_labels: NotRequired[dict[str, str]]
    tab_id: Required[str]
    terminal_id: Required[str]
    terminal_title: NotRequired[str | None]
    terminal_title_stripped: NotRequired[str | None]
    title: NotRequired[str | None]
    tokens: NotRequired[dict[str, str]]
    workspace_id: Required[str]


class EventPaneLayoutPane(TypedDict):
    focused: bool
    pane_id: str
    rect: EventPaneLayoutRect


class EventPaneLayoutRect(TypedDict):
    height: int
    width: int
    x: int
    y: int


class EventPaneLayoutSnapshot(TypedDict):
    area: EventPaneLayoutRect
    focused_pane_id: str
    panes: list[EventPaneLayoutPane]
    splits: list[EventPaneLayoutSplit]
    tab_id: str
    workspace_id: str
    zoomed: bool


class EventPaneLayoutSplit(TypedDict):
    direction: EventSplitDirection
    id: str
    ratio: int
    rect: EventPaneLayoutRect


class EventPaneScrollInfo(TypedDict):
    max_offset_from_bottom: int
    offset_from_bottom: int
    viewport_rows: int


type EventSplitDirection = Literal["right", "down"]


class EventTabInfo(TypedDict):
    agent_status: EventAgentStatus
    focused: bool
    label: str
    number: int
    pane_count: int
    tab_id: str
    workspace_id: str


class EventWorkspaceInfo(TypedDict, total=False):
    active_tab_id: Required[str]
    agent_status: Required[EventAgentStatus]
    focused: Required[bool]
    label: Required[str]
    number: Required[int]
    pane_count: Required[int]
    tab_count: Required[int]
    tokens: NotRequired[dict[str, str]]
    workspace_id: Required[str]
    worktree: NotRequired[EventWorkspaceWorktreeInfo | None]


class EventWorkspaceWorktreeInfo(TypedDict):
    checkout_path: str
    is_linked_worktree: bool
    repo_key: str
    repo_name: str
    repo_root: str


class EventWorktreeInfo(TypedDict, total=False):
    branch: NotRequired[str | None]
    is_bare: Required[bool]
    is_detached: Required[bool]
    is_linked_worktree: Required[bool]
    is_prunable: Required[bool]
    label: Required[str]
    open_workspace_id: NotRequired[str | None]
    path: Required[str]


# Discriminated aliases

type ResponseResultPong = ResponseResponseResultVariant1
type ResponseResultSessionSnapshot = ResponseResponseResultVariant2
type ResponseResultWorkspaceInfo = ResponseResponseResultVariant3
type ResponseResultWorkspaceCreated = ResponseResponseResultVariant4
type ResponseResultWorkspaceList = ResponseResponseResultVariant5
type ResponseResultWorktreeList = ResponseResponseResultVariant6
type ResponseResultWorktreeCreated = ResponseResponseResultVariant7
type ResponseResultWorktreeOpened = ResponseResponseResultVariant8
type ResponseResultWorktreeRemoved = ResponseResponseResultVariant9
type ResponseResultTabInfo = ResponseResponseResultVariant10
type ResponseResultTabCreated = ResponseResponseResultVariant11
type ResponseResultTabList = ResponseResponseResultVariant12
type ResponseResultAgentInfo = ResponseResponseResultVariant13
type ResponseResultAgentStarted = ResponseResponseResultVariant14
type ResponseResultAgentPrompted = ResponseResponseResultVariant15
type ResponseResultAgentList = ResponseResponseResultVariant16
type ResponseResultAgentView = ResponseResponseResultVariant17
type ResponseResultPaneInfo = ResponseResponseResultVariant18
type ResponseResultPaneList = ResponseResponseResultVariant19
type ResponseResultPaneCurrent = ResponseResponseResultVariant20
type ResponseResultPaneSwap = ResponseResponseResultVariant21
type ResponseResultPaneMove = ResponseResponseResultVariant22
type ResponseResultPaneZoom = ResponseResponseResultVariant23
type ResponseResultPaneLayout = ResponseResponseResultVariant24
type ResponseResultPaneProcessInfo = ResponseResponseResultVariant25
type ResponseResultLayoutExport = ResponseResponseResultVariant26
type ResponseResultLayoutApply = ResponseResponseResultVariant27
type ResponseResultLayoutSplitRatioSet = ResponseResponseResultVariant28
type ResponseResultPaneNeighbor = ResponseResponseResultVariant29
type ResponseResultPaneEdges = ResponseResponseResultVariant30
type ResponseResultPaneFocusDirection = ResponseResponseResultVariant31
type ResponseResultPaneResize = ResponseResponseResultVariant32
type ResponseResultPaneRead = ResponseResponseResultVariant33
type ResponseResultPaneSelection = ResponseResponseResultVariant34
type ResponseResultPaneCopyMotion = ResponseResponseResultVariant35
type ResponseResultPaneCopySearch = ResponseResponseResultVariant36
type ResponseResultPaneGraphicsFrameAck = ResponseResponseResultVariant37
type ResponseResultPaneGraphicsInfo = ResponseResponseResultVariant38
type ResponseResultAgentExplain = ResponseResponseResultVariant39
type ResponseResultSubscriptionStarted = ResponseResponseResultVariant40
type ResponseResultWaitMatched = ResponseResponseResultVariant41
type ResponseResultOutputMatched = ResponseResponseResultVariant42
type ResponseResultNotificationShow = ResponseResponseResultVariant43
type ResponseResultClientWindowTitle = ResponseResponseResultVariant44
type ResponseResultIntegrationList = ResponseResponseResultVariant45
type ResponseResultIntegrationInstall = ResponseResponseResultVariant46
type ResponseResultIntegrationUninstall = ResponseResponseResultVariant47
type ResponseResultAgentManifestReload = ResponseResponseResultVariant48
type ResponseResultAgentManifestStatus = ResponseResponseResultVariant49
type ResponseResultPluginLinked = ResponseResponseResultVariant50
type ResponseResultPluginList = ResponseResponseResultVariant51
type ResponseResultPluginUnlinked = ResponseResponseResultVariant52
type ResponseResultPluginEnabled = ResponseResponseResultVariant53
type ResponseResultPluginDisabled = ResponseResponseResultVariant54
type ResponseResultPluginActionList = ResponseResponseResultVariant55
type ResponseResultPluginActionInvoked = ResponseResponseResultVariant56
type ResponseResultPaneLinkResolved = ResponseResponseResultVariant57
type ResponseResultPaneLinkActivated = ResponseResponseResultVariant58
type ResponseResultPluginLogList = ResponseResponseResultVariant59
type ResponseResultPluginPaneOpened = ResponseResponseResultVariant60
type ResponseResultPluginPaneFocused = ResponseResponseResultVariant61
type ResponseResultPluginPaneClosed = ResponseResponseResultVariant62
type ResponseResultConfigReload = ResponseResponseResultVariant63
type ResponseResultClientShellSurfaceSet = ResponseResponseResultVariant64
type ResponseResultOk = ResponseResponseResultVariant65

type EventDataWorkspaceCreated = EventEventDataVariant1
type EventDataWorkspaceUpdated = EventEventDataVariant2
type EventDataWorkspaceMetadataUpdated = EventEventDataVariant3
type EventDataWorkspaceClosed = EventEventDataVariant4
type EventDataWorkspaceRenamed = EventEventDataVariant5
type EventDataWorkspaceMoved = EventEventDataVariant6
type EventDataWorkspaceReordered = EventEventDataVariant7
type EventDataWorkspaceFocused = EventEventDataVariant8
type EventDataWorktreeCreated = EventEventDataVariant9
type EventDataWorktreeOpened = EventEventDataVariant10
type EventDataWorktreeRemoved = EventEventDataVariant11
type EventDataTabCreated = EventEventDataVariant12
type EventDataTabClosed = EventEventDataVariant13
type EventDataTabRenamed = EventEventDataVariant14
type EventDataTabMoved = EventEventDataVariant15
type EventDataTabFocused = EventEventDataVariant16
type EventDataPaneCreated = EventEventDataVariant17
type EventDataPaneClosed = EventEventDataVariant18
type EventDataPaneUpdated = EventEventDataVariant19
type EventDataPaneFocused = EventEventDataVariant20
type EventDataPaneMoved = EventEventDataVariant21
type EventDataPaneOutputChanged = EventEventDataVariant22
type EventDataPaneExited = EventEventDataVariant23
type EventDataPaneAgentDetected = EventEventDataVariant24
type EventDataPaneAgentStatusChanged = EventEventDataVariant25
type EventDataLayoutUpdated = EventEventDataVariant26

# Top-level schema unions

type RequestMethod = Literal[
    "ping",
    "server.stop",
    "server.live_handoff",
    "server.reload_config",
    "server.agent_manifests",
    "server.reload_agent_manifests",
    "notification.show",
    "product_announcement.dismiss",
    "release_notes.dismiss",
    "command.invoke",
    "client.window_title.set",
    "client.window_title.clear",
    "client_shell.surface.set",
    "session.snapshot",
    "workspace.create",
    "workspace.list",
    "workspace.get",
    "workspace.focus",
    "workspace.rename",
    "workspace.move",
    "workspace.move_block",
    "workspace.report_metadata",
    "workspace.close",
    "worktree.list",
    "worktree.create",
    "worktree.open",
    "worktree.remove",
    "tab.create",
    "tab.list",
    "tab.get",
    "tab.focus",
    "tab.rename",
    "tab.move",
    "tab.close",
    "agent.list",
    "agent.get",
    "agent.read",
    "agent.explain",
    "agent.send_keys",
    "agent.rename",
    "agent.view.set",
    "agent.view.clear",
    "agent.focus",
    "agent.start",
    "agent.prompt",
    "agent.wait",
    "pane.split",
    "pane.swap",
    "pane.move",
    "pane.zoom",
    "pane.layout",
    "pane.process_info",
    "layout.export",
    "layout.apply",
    "layout.set_split_ratio",
    "pane.neighbor",
    "pane.edges",
    "pane.focus_direction",
    "pane.resize",
    "pane.scroll",
    "pane.edit_scrollback",
    "pane.selection.read",
    "pane.copy_motion",
    "pane.copy_search",
    "pane.list",
    "pane.current",
    "pane.get",
    "pane.focus",
    "pane.input.set",
    "pane.link.activate",
    "pane.link.resolve",
    "pane.rename",
    "pane.send_text",
    "pane.send_keys",
    "pane.send_input",
    "pane.read",
    "pane.graphics.set",
    "pane.graphics.clear",
    "pane.graphics.info",
    "pane.report_agent",
    "pane.report_agent_session",
    "pane.report_metadata",
    "pane.clear_agent_authority",
    "pane.release_agent",
    "pane.close",
    "popup.close",
    "events.subscribe",
    "events.wait",
    "pane.wait_for_output",
    "integration.list",
    "integration.install",
    "integration.uninstall",
    "plugin.link",
    "plugin.list",
    "plugin.unlink",
    "plugin.enable",
    "plugin.disable",
    "plugin.action.list",
    "plugin.action.invoke",
    "plugin.log.list",
    "plugin.pane.open",
    "plugin.pane.focus",
    "plugin.pane.close",
]
type RequestParams = (
    RequestPingParams
    | RequestEmptyParams
    | RequestServerLiveHandoffParams
    | RequestNotificationShowParams
    | RequestProductAnnouncementDismissParams
    | RequestReleaseNotesDismissParams
    | RequestCommandInvokeParams
    | RequestClientWindowTitleSetParams
    | RequestClientShellSurfaceSetParams
    | RequestWorkspaceCreateParams
    | RequestWorkspaceTarget
    | RequestWorkspaceRenameParams
    | RequestWorkspaceMoveParams
    | RequestWorkspaceMoveBlockParams
    | RequestWorkspaceReportMetadataParams
    | RequestWorkspaceCloseParams
    | RequestWorktreeListParams
    | RequestWorktreeCreateParams
    | RequestWorktreeOpenParams
    | RequestWorktreeRemoveParams
    | RequestTabCreateParams
    | RequestTabListParams
    | RequestTabTarget
    | RequestTabRenameParams
    | RequestTabMoveParams
    | RequestAgentTarget
    | RequestAgentReadParams
    | RequestAgentSendKeysParams
    | RequestAgentRenameParams
    | RequestAgentViewSetParams
    | RequestAgentViewClearParams
    | RequestAgentStartParams
    | RequestAgentPromptParams
    | RequestAgentWaitParams
    | RequestPaneSplitParams
    | RequestPaneSwapParams
    | RequestPaneMoveParams
    | RequestPaneZoomParams
    | RequestPaneLayoutParams
    | RequestPaneProcessInfoParams
    | RequestLayoutExportParams
    | RequestLayoutApplyParams
    | RequestLayoutSetSplitRatioParams
    | RequestPaneNeighborParams
    | RequestPaneEdgesParams
    | RequestPaneFocusDirectionParams
    | RequestPaneResizeParams
    | RequestPaneScrollParams
    | RequestPaneTarget
    | RequestPaneSelectionReadParams
    | RequestPaneCopyMotionParams
    | RequestPaneCopySearchParams
    | RequestPaneListParams
    | RequestPaneCurrentParams
    | RequestPaneInputSetParams
    | RequestPaneLinkActivateParams
    | RequestPaneRenameParams
    | RequestPaneSendTextParams
    | RequestPaneSendKeysParams
    | RequestPaneSendInputParams
    | RequestPaneReadParams
    | RequestPaneGraphicsSetParams
    | RequestPaneGraphicsClearParams
    | RequestPaneReportAgentParams
    | RequestPaneReportAgentSessionParams
    | RequestPaneReportMetadataParams
    | RequestPaneClearAgentAuthorityParams
    | RequestPaneReleaseAgentParams
    | RequestEventsSubscribeParams
    | RequestEventsWaitParams
    | RequestPaneWaitForOutputParams
    | RequestIntegrationInstallParams
    | RequestIntegrationUninstallParams
    | RequestPluginLinkParams
    | RequestPluginListParams
    | RequestPluginUnlinkParams
    | RequestPluginSetEnabledParams
    | RequestPluginActionListParams
    | RequestPluginActionInvokeParams
    | RequestPluginLogListParams
    | RequestPluginPaneOpenParams
    | RequestPluginPaneFocusParams
    | RequestPluginPaneCloseParams
)
