from typing import NoReturn

STUB_METHODS: frozenset[str]

class SyncMethodStubs:
    def agent_explain(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_get(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_prompt(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_read(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_rename(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_send_keys(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_start(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_view_clear(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_view_set(self, *args: object, **kwargs: object) -> NoReturn: ...
    def agent_wait(self, *args: object, **kwargs: object) -> NoReturn: ...
    def client_shell_surface_set(self, *args: object, **kwargs: object) -> NoReturn: ...
    def client_window_title_clear(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    def client_window_title_set(self, *args: object, **kwargs: object) -> NoReturn: ...
    def command_invoke(self, *args: object, **kwargs: object) -> NoReturn: ...
    def events_wait(self, *args: object, **kwargs: object) -> NoReturn: ...
    def integration_install(self, *args: object, **kwargs: object) -> NoReturn: ...
    def integration_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    def integration_uninstall(self, *args: object, **kwargs: object) -> NoReturn: ...
    def layout_apply(self, *args: object, **kwargs: object) -> NoReturn: ...
    def layout_export(self, *args: object, **kwargs: object) -> NoReturn: ...
    def layout_set_split_ratio(self, *args: object, **kwargs: object) -> NoReturn: ...
    def notification_show(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_clear_agent_authority(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    def pane_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_copy_motion(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_copy_search(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_current(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_edges(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_edit_scrollback(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_focus_direction(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_get(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_graphics_clear(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_graphics_info(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_graphics_set(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_graphics_stream(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_input_set(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_layout(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_link_activate(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_link_resolve(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_move(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_neighbor(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_process_info(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_release_agent(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_rename(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_report_agent(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_report_agent_session(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    def pane_report_metadata(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_resize(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_scroll(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_selection_read(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_split(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_swap(self, *args: object, **kwargs: object) -> NoReturn: ...
    def pane_zoom(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_action_invoke(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_action_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_disable(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_enable(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_link(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_log_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_pane_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_pane_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_pane_open(self, *args: object, **kwargs: object) -> NoReturn: ...
    def plugin_unlink(self, *args: object, **kwargs: object) -> NoReturn: ...
    def popup_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    def product_announcement_dismiss(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    def release_notes_dismiss(self, *args: object, **kwargs: object) -> NoReturn: ...
    def server_agent_manifests(self, *args: object, **kwargs: object) -> NoReturn: ...
    def server_live_handoff(self, *args: object, **kwargs: object) -> NoReturn: ...
    def server_reload_agent_manifests(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    def server_reload_config(self, *args: object, **kwargs: object) -> NoReturn: ...
    def server_stop(self, *args: object, **kwargs: object) -> NoReturn: ...
    def session_snapshot(self, *args: object, **kwargs: object) -> NoReturn: ...
    def tab_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    def tab_create(self, *args: object, **kwargs: object) -> NoReturn: ...
    def tab_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    def tab_get(self, *args: object, **kwargs: object) -> NoReturn: ...
    def tab_move(self, *args: object, **kwargs: object) -> NoReturn: ...
    def tab_rename(self, *args: object, **kwargs: object) -> NoReturn: ...
    def workspace_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    def workspace_create(self, *args: object, **kwargs: object) -> NoReturn: ...
    def workspace_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    def workspace_get(self, *args: object, **kwargs: object) -> NoReturn: ...
    def workspace_move(self, *args: object, **kwargs: object) -> NoReturn: ...
    def workspace_move_block(self, *args: object, **kwargs: object) -> NoReturn: ...
    def workspace_rename(self, *args: object, **kwargs: object) -> NoReturn: ...
    def workspace_report_metadata(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    def worktree_create(self, *args: object, **kwargs: object) -> NoReturn: ...
    def worktree_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    def worktree_open(self, *args: object, **kwargs: object) -> NoReturn: ...
    def worktree_remove(self, *args: object, **kwargs: object) -> NoReturn: ...

class AsyncMethodStubs:
    async def agent_explain(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_get(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_prompt(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_read(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_rename(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_send_keys(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_start(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_view_clear(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_view_set(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def agent_wait(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def client_shell_surface_set(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def client_window_title_clear(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def client_window_title_set(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def command_invoke(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def events_wait(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def integration_install(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def integration_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def integration_uninstall(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def layout_apply(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def layout_export(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def layout_set_split_ratio(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def notification_show(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_clear_agent_authority(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def pane_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_copy_motion(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_copy_search(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_current(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_edges(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_edit_scrollback(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def pane_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_focus_direction(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def pane_get(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_graphics_clear(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def pane_graphics_info(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_graphics_set(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_graphics_stream(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def pane_input_set(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_layout(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_link_activate(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_link_resolve(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_move(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_neighbor(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_process_info(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_release_agent(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_rename(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_report_agent(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_report_agent_session(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def pane_report_metadata(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def pane_resize(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_scroll(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_selection_read(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def pane_split(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_swap(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def pane_zoom(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_action_invoke(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def plugin_action_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_disable(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_enable(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_link(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_log_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_pane_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_pane_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_pane_open(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def plugin_unlink(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def popup_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def product_announcement_dismiss(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def release_notes_dismiss(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def server_agent_manifests(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def server_live_handoff(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def server_reload_agent_manifests(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def server_reload_config(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def server_stop(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def session_snapshot(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def tab_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def tab_create(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def tab_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def tab_get(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def tab_move(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def tab_rename(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def workspace_close(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def workspace_create(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def workspace_focus(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def workspace_get(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def workspace_move(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def workspace_move_block(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def workspace_rename(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def workspace_report_metadata(
        self, *args: object, **kwargs: object
    ) -> NoReturn: ...
    async def worktree_create(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def worktree_list(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def worktree_open(self, *args: object, **kwargs: object) -> NoReturn: ...
    async def worktree_remove(self, *args: object, **kwargs: object) -> NoReturn: ...
